export const MOCK_EVENTS = [
  {
    eventId: "e1",
    organizerId: "org-daiict",
    title: "Tarang",
    description: "The spectacular signature cultural Garba night celebrating rhythm and campus tradition.",
    category: "FESTIVAL",
    city: "Gandhinagar",
    venue: "DAIICT Campus",
    startDate: "11 OCT 2026",
    poster: "T",
  },
  {
    eventId: "e2",
    organizerId: "org-daiict",
    title: "Synapse",
    description: "An explosive, multi-stage music concert experience bringing massive student energy.",
    category: "CONCERT",
    city: "Gandhinagar",
    venue: "DAIICT Campus",
    startDate: "20 FEB 2027",
    poster: "S",
  },
  {
    eventId: "e3",
    organizerId: "org-daiict",
    title: "i.Fest",
    description: "The premier technical festival showcasing cutting-edge development, hackathons, and designs.",
    category: "HACKATHON",
    city: "Gandhinagar",
    venue: "DAIICT Campus",
    startDate: "06 NOV 2026",
    poster: "I",
  },
  {
    eventId: "e4",
    organizerId: "org-daiict",
    title: "Concours",
    description: "The high-intensity multi-sport championship arena testing skill, speed, and strategy.",
    category: "SPORTS",
    city: "Gandhinagar",
    venue: "DAIICT Campus",
    startDate: "26 OCT 2026",
    poster: "C",
  },
  {
    eventId: "e5",
    organizerId: "org-daiict",
    title: "Mood Indigo",
    description: "A monumental live concert production presenting world-class musical talent.",
    category: "CONCERT",
    city: "Gandhinagar",
    venue: "DAIICT Campus",
    startDate: "15 DEC 2026",
    poster: "M",
  },
  {
    eventId: "e6",
    organizerId: "org-iitgn",
    title: "Amalthea",
    description: "An annual pinnacle concert gathering student crowds for an immersive auditory experience.",
    category: "CONCERT",
    city: "Gandhinagar",
    venue: "IIT Gandhinagar",
    startDate: "20 MAR 2027",
    poster: "A",
  },
  {
    eventId: "e7",
    organizerId: "org-iima",
    title: "Chaos",
    description: "The legendary, high-octane cultural concert featuring top-tier live entertainment performance setups.",
    category: "CONCERT",
    city: "Ahmedabad",
    venue: "IIM Ahmedabad",
    startDate: "10 MAR 2027",
    poster: "C",
  },
  {
    eventId: "e8",
    organizerId: "org-bitsg",
    title: "Waves",
    description: "The iconic beachfront musical main-stage weekend highlighting elite indie performance lineups.",
    category: "CONCERT",
    city: "Goa",
    venue: "BITS Goa Campus",
    startDate: "01 NOV 2026",
    poster: "W",
  }
];